services:
    _defaults:
        public: true
        autowire: true

    Ssch\TYPO3Rector\:
        resource: '../src/'
        exclude:
            - '../src/{Rector/**/*Rector.php}'
            - '../src/Console'
