name: Coding Standard

on:
    pull_request: null
    push:
        branches:
            - "master"

jobs:
    coding_standard:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2.0.0
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: none

            -   run: composer install --no-progress
            -   run: vendor/bin/ecs check --fix

            -   uses: stefanzweifel/git-auto-commit-action@v2.5.0
                with:
                    commit_message: Apply coding standard changes
                    branch: "master"
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
